// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"gorm.io/gorm"
	"order_service/internal/broker"
	"order_service/internal/controller"
	"order_service/internal/database"
	"order_service/internal/repository"
	"order_service/internal/router"
	"order_service/internal/usecase"
)

// Injectors from injector.go:

func InitializeServer() (*App, error) {
	db, err := database.Connect()
	if err != nil {
		return nil, err
	}
	orderRepository := repository.NewOrderRepository(db)
	validate := NewValidator()
	rabbitMQ := NewRabbitMQ()
	orderUsecase := usecase.NewOrderUsecase(orderRepository, validate, rabbitMQ)
	orderController := controller.NewOrderController(orderUsecase)
	engine := router.SetupRouter(orderController)
	app := &App{
		DB:     db,
		Router: engine,
	}
	return app, nil
}

// injector.go:

type App struct {
	DB     *gorm.DB
	Router *gin.Engine
}

func NewValidator() *validator.Validate {
	return validator.New()
}

func NewRabbitMQ() *broker.RabbitMQ {
	return broker.NewRabbitMQ("amqp://guest:guest@localhost:5672/")
}

var repositorySet = wire.NewSet(repository.NewOrderRepository)

var usecaseSet = wire.NewSet(usecase.NewOrderUsecase)

var controllerSet = wire.NewSet(controller.NewOrderController)

var routerSet = wire.NewSet(router.SetupRouter)
