// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"gorm.io/gorm"
	"payment_service/internal/broker"
	"payment_service/internal/controller"
	"payment_service/internal/database"
	"payment_service/internal/repository"
	"payment_service/internal/router"
	"payment_service/internal/service"
	"payment_service/internal/usecase"
)

// Injectors from injector.go:

func InitializeServer() (*App, error) {
	db, err := database.Connect()
	if err != nil {
		return nil, err
	}
	paymentRepository := repository.NewPaymentRepository(db)
	validate := NewValidator()
	midtransService := service.NewMidtransService()
	rabbitMQ, err := NewRabbitMQ()
	if err != nil {
		return nil, err
	}
	publisher := NewPublisher(rabbitMQ)
	paymentUsecase := usecase.NewPaymentUsecase(paymentRepository, validate, midtransService, publisher)
	paymentController := controller.NewPaymentController(paymentUsecase)
	engine := router.SetupRouter(paymentController)
	app := &App{
		DB:         db,
		Router:     engine,
		Consumer:   rabbitMQ,
		Controller: paymentController,
	}
	return app, nil
}

// injector.go:

type App struct {
	DB         *gorm.DB
	Router     *gin.Engine
	Consumer   *broker.RabbitMQ
	Controller controller.PaymentController
}

func NewValidator() *validator.Validate {
	return validator.New()
}

func NewRabbitMQ() (*broker.RabbitMQ, error) {
	return broker.NewConsumer("amqp://guest:guest@localhost:5672/")
}

func NewPublisher(rmq *broker.RabbitMQ) broker.Publisher {
	return rmq
}

var brokerSet = wire.NewSet(
	NewRabbitMQ,
	NewPublisher,
)

var repositorySet = wire.NewSet(repository.NewPaymentRepository)

var midtransServiceSet = wire.NewSet(service.NewMidtransService)

var usecaseSet = wire.NewSet(usecase.NewPaymentUsecase)

var controllerSet = wire.NewSet(controller.NewPaymentController)

var routerSet = wire.NewSet(router.SetupRouter)
