// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"gorm.io/gorm"
	"notification_service/internal/consumer"
	"notification_service/internal/controller"
	"notification_service/internal/database"
	"notification_service/internal/repository"
	"notification_service/internal/router"
	"notification_service/internal/usecase"
)

// Injectors from injector.go:

func InitializeServer() (*App, error) {
	db, err := database.Connect()
	if err != nil {
		return nil, err
	}
	notificationRepository := repository.NewNotificationRepository(db)
	validate := NewValidator()
	notificationUsecase := usecase.NewNotificationUsecase(notificationRepository, validate)
	notificationController := controller.NewNotificationController(notificationUsecase)
	engine := router.SetupRouter(notificationController)
	string2 := NewRabbitURL()
	consumerConsumer, err := consumer.NewConsumer(string2)
	if err != nil {
		return nil, err
	}
	app := &App{
		DB:         db,
		Router:     engine,
		Consumer:   consumerConsumer,
		Controller: notificationController,
	}
	return app, nil
}

// injector.go:

type App struct {
	DB         *gorm.DB
	Router     *gin.Engine
	Consumer   *consumer.Consumer
	Controller controller.NotificationController
}

func NewValidator() *validator.Validate {
	return validator.New()
}

func NewRabbitURL() string {
	return "amqp://guest:guest@localhost:5672/"
}

var consumerSet = wire.NewSet(
	NewRabbitURL, consumer.NewConsumer,
)

var repositorySet = wire.NewSet(repository.NewNotificationRepository)

var usecaseSet = wire.NewSet(usecase.NewNotificationUsecase)

var controllerSet = wire.NewSet(controller.NewNotificationController)

var routerSet = wire.NewSet(router.SetupRouter)
